# Generated by Django 4.2.2 on 2023-06-20 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'managed': True, 'ordering': ['order_num'], 'verbose_name': 'Tasks', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='complite_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vazifani topshirish vaqti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=300, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='add_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Vazifa berilayotgan vaqt'),
        ),
    ]
