# Generated by Django 4.2.2 on 2023-06-22 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_tasks_options_tasks_active_tasks_complite_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_authors', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tasks')),
                ('to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_tos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Izohlar',
                'verbose_name_plural': 'Izohlar',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
