# Generated by Django 4.2.2 on 2023-06-22 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_commenttasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', django_quill.fields.QuillField(blank=True, null=True)),
                ('file', models.FileField(upload_to='file/answers/%Y-%m-%d/')),
                ('checked', models.BooleanField(default=False)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_students', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tasks')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Javoblar',
                'verbose_name_plural': 'Javoblar',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
